#!/bin/bash

# NOTE: to be included in other scripts
#       e.g. # . ./versions.sh

# VERSIONS
DATANET_VERSION="0.1.1"
OPEN_RESTY_VERSION="1.9.7.3"
DATANET_OPEN_RESTY_VERSION="${OPEN_RESTY_VERSION}_${DATANET_VERSION}"

DATANET_PREFIX="datanet"
DATANET_CENTRAL_PREFIX="${DATANET_PREFIX}_central"
OPEN_RESTY_PREFIX="${DATANET_PREFIX}_openresty"

DATANET_TEMP_DIR="${DATANET_PREFIX}_${DATANET_VERSION}"
DATANET_TARBALL="${DATANET_TEMP_DIR}.tgz"

DATANET_CENTRAL_TEMP_DIR="${DATANET_CENTRAL_PREFIX}_${DATANET_VERSION}"
DATANET_CENTRAL_TARBALL="${DATANET_CENTRAL_TEMP_DIR}.tgz"

OPEN_RESTY_TEMP_DIR="${OPEN_RESTY_PREFIX}_${DATANET_OPEN_RESTY_VERSION}"
DATANET_OPEN_RESTY_TARBALL="${OPEN_RESTY_TEMP_DIR}.tgz"

# SETTINGS
DATANET_CENTRAL_REDIS_PORT=6000

# SETUP
OPENRESTY_BASE_DIR="/usr/local/openresty"
OPENRESTY_INSTALL_DIR="${OPENRESTY_BASE_DIR}/lualib"
DATANET_INSTALL_DIR="/usr/local/datanet"

AGENT_DATABASE_DIRECTORY="./data/memory_dbs"

